/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as ProviseursRouteImport } from './routes/proviseurs'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as FicheTechniqueRouteImport } from './routes/fiche-technique'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviseursRoute = ProviseursRouteImport.update({
  id: '/proviseurs',
  path: '/proviseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const FicheTechniqueRoute = FicheTechniqueRouteImport.update({
  id: '/fiche-technique',
  path: '/fiche-technique',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/fiche-technique': typeof FicheTechniqueRoute
  '/historique': typeof HistoriqueRoute
  '/personnel': typeof PersonnelRoute
  '/proviseurs': typeof ProviseursRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/fiche-technique': typeof FicheTechniqueRoute
  '/historique': typeof HistoriqueRoute
  '/personnel': typeof PersonnelRoute
  '/proviseurs': typeof ProviseursRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/fiche-technique': typeof FicheTechniqueRoute
  '/historique': typeof HistoriqueRoute
  '/personnel': typeof PersonnelRoute
  '/proviseurs': typeof ProviseursRoute
  '/resultats': typeof ResultatsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/documents'
    | '/fiche-technique'
    | '/historique'
    | '/personnel'
    | '/proviseurs'
    | '/resultats'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/documents'
    | '/fiche-technique'
    | '/historique'
    | '/personnel'
    | '/proviseurs'
    | '/resultats'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/documents'
    | '/fiche-technique'
    | '/historique'
    | '/personnel'
    | '/proviseurs'
    | '/resultats'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  FicheTechniqueRoute: typeof FicheTechniqueRoute
  HistoriqueRoute: typeof HistoriqueRoute
  PersonnelRoute: typeof PersonnelRoute
  ProviseursRoute: typeof ProviseursRoute
  ResultatsRoute: typeof ResultatsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proviseurs': {
      id: '/proviseurs'
      path: '/proviseurs'
      fullPath: '/proviseurs'
      preLoaderRoute: typeof ProviseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiche-technique': {
      id: '/fiche-technique'
      path: '/fiche-technique'
      fullPath: '/fiche-technique'
      preLoaderRoute: typeof FicheTechniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  FicheTechniqueRoute: FicheTechniqueRoute,
  HistoriqueRoute: HistoriqueRoute,
  PersonnelRoute: PersonnelRoute,
  ProviseursRoute: ProviseursRoute,
  ResultatsRoute: ResultatsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
